/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.io.*;
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author jakub
 */
public class CategoryScreen extends javax.swing.JFrame {

    /**
     * Creates new form CategoryScreen
     */
    public CategoryScreen() {
        initComponents();
    }
    
    public CategoryScreen(String wordsSetNameStr) {
        initComponents();
        this.wordsSetName.setText(wordsSetNameStr);
        this.category = wordsSetNameStr;
        readJsonFile();
        setLanguages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterWords = new javax.swing.JLabel();
        language1label = new javax.swing.JLabel();
        language2label = new javax.swing.JLabel();
        enField1 = new javax.swing.JTextField();
        polField1 = new javax.swing.JTextField();
        enField2 = new javax.swing.JTextField();
        polField2 = new javax.swing.JTextField();
        enField3 = new javax.swing.JTextField();
        polField3 = new javax.swing.JTextField();
        enField4 = new javax.swing.JTextField();
        polField4 = new javax.swing.JTextField();
        enField5 = new javax.swing.JTextField();
        polField5 = new javax.swing.JTextField();
        performExam = new javax.swing.JButton();
        prevButt = new javax.swing.JButton();
        wordsSetName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interactive dictionary");
        setResizable(false);

        enterWords.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        enterWords.setText("Enter words for set:");

        language1label.setText("English");

        language2label.setText("Polish");

        enField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enField1FocusLost(evt);
            }
        });

        polField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                polField1FocusLost(evt);
            }
        });

        enField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enField2FocusLost(evt);
            }
        });

        polField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                polField2FocusLost(evt);
            }
        });

        enField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enField3FocusLost(evt);
            }
        });

        polField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                polField3FocusLost(evt);
            }
        });

        enField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enField4FocusLost(evt);
            }
        });

        polField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                polField4FocusLost(evt);
            }
        });

        enField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enField5FocusLost(evt);
            }
        });

        polField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                polField5FocusLost(evt);
            }
        });

        performExam.setText("Perform exam");
        performExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performExamActionPerformed(evt);
            }
        });

        prevButt.setText("Previous");
        prevButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtActionPerformed(evt);
            }
        });

        wordsSetName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        wordsSetName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(prevButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(performExam)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(language1label)
                                .addGap(178, 178, 178)
                                .addComponent(language2label))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(polField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(polField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(polField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enField4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(polField4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enField5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(polField5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(enterWords))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wordsSetName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(enterWords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordsSetName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(language1label)
                    .addComponent(language2label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevButt)
                    .addComponent(performExam))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readJsonFile() {
        JSONParser parser = new JSONParser();
        
        try {
            Object obj = parser.parse(new FileReader("wordsSet.json"));
            this.jsonObj = (JSONObject) obj;
        }
        catch(FileNotFoundException e) { e.printStackTrace(); }
        catch(IOException e) { e.printStackTrace(); }
        catch(ParseException e) { e.printStackTrace(); }
        catch(Exception e) { e.printStackTrace(); }
    }
    
    // TODO Make this json human readable
    private void writeToJsonFile() throws IOException {
        System.out.println("Action performed");
        
        JSONArray cat = new JSONArray();
        
        JSONObject jsonInCat = new JSONObject();
        jsonInCat.put("language1", this.language1);
        jsonInCat.put("language2", this.language2);
        jsonInCat.put("words1", this.words1);
        jsonInCat.put("words2", this.words2);
        
        cat.add(jsonInCat);
        jsonObj.put(this.category, cat);
        
        try {
            FileWriter file = new FileWriter("wordsSet.json");
            file.write(jsonObj.toJSONString());
            file.flush();
            System.out.println("JSON object: " + jsonObj);
        }
        catch(IOException e) { e.printStackTrace(); }

    }
    
    private void performExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performExamActionPerformed
        try { writeToJsonFile(); }
        catch(IOException e) { e.printStackTrace(); }
    }//GEN-LAST:event_performExamActionPerformed

    private void prevButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtActionPerformed
        DictionaryGUI mainScreen = new DictionaryGUI();
        mainScreen.setLocationRelativeTo(null);
        mainScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prevButtActionPerformed

    // TODO consider case when string is empty
    // TODO make loop for buttons - in automatic way
    
    private void enField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enField1FocusLost
        words1.add(enField1.getText());
    }//GEN-LAST:event_enField1FocusLost

    private void enField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enField2FocusLost
        words1.add(enField2.getText());
    }//GEN-LAST:event_enField2FocusLost

    private void enField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enField3FocusLost
        words1.add(enField3.getText());
    }//GEN-LAST:event_enField3FocusLost

    private void enField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enField4FocusLost
        words1.add(enField4.getText());
    }//GEN-LAST:event_enField4FocusLost

    private void enField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enField5FocusLost
        words1.add(enField5.getText());
    }//GEN-LAST:event_enField5FocusLost

    private void polField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_polField1FocusLost
        words2.add(polField1.getText());
    }//GEN-LAST:event_polField1FocusLost

    private void polField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_polField2FocusLost
        words2.add(polField2.getText());
    }//GEN-LAST:event_polField2FocusLost

    private void polField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_polField3FocusLost
        words2.add(polField3.getText());
    }//GEN-LAST:event_polField3FocusLost

    private void polField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_polField4FocusLost
        words2.add(polField4.getText());
    }//GEN-LAST:event_polField4FocusLost

    private void polField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_polField5FocusLost
        words2.add(polField5.getText());
    }//GEN-LAST:event_polField5FocusLost

    // TODO Make languages available to choose
    private void setLanguages() {
        this.language1 = language1label.getText();
        this.language2 = language2label.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryScreen().setVisible(true);
            }
        });
    }

    private JSONObject jsonObj;
    private String category;
    private String language1;
    private String language2;
    private ArrayList<String> words1 = new ArrayList<String>();
    private ArrayList<String> words2 = new ArrayList<String>();
//    private String[] words1;
//    private String[] words2;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enField1;
    private javax.swing.JTextField enField2;
    private javax.swing.JTextField enField3;
    private javax.swing.JTextField enField4;
    private javax.swing.JTextField enField5;
    private javax.swing.JLabel enterWords;
    private javax.swing.JLabel language1label;
    private javax.swing.JLabel language2label;
    private javax.swing.JButton performExam;
    private javax.swing.JTextField polField1;
    private javax.swing.JTextField polField2;
    private javax.swing.JTextField polField3;
    private javax.swing.JTextField polField4;
    private javax.swing.JTextField polField5;
    private javax.swing.JButton prevButt;
    private javax.swing.JLabel wordsSetName;
    // End of variables declaration//GEN-END:variables
}
